export default function PrivacyPolicy() {
  return (
    <div className="bg-[#38bdf8] pt-5 ">
      <div className="flex justify-center">
        <h1 className="text-6xl text-white border-b-4 border-black">
          Privacy Policy
        </h1>
      </div>
      <div className="p-16">
        <div className="flex justify-center flex-col p-5 shadow-2xl border border-gray-200 rounded-sm bg-white">
          <p>
             Our Store (“we,” “our,” or “us”) is committed to protecting
            your privacy. This Privacy Policy explains how your personal
            information is collected, used, and disclosed by  Our Store.{' '}
            <br />
            <br />
            This Privacy Policy applies to our website, and its associated
            subdomains (collectively, our “website”) alongside our application,
             Our Store. By accessing or using our website, you signify that
            you have read, understood, and agree to our collection, storage,
            use, and disclosure of your personal information as described in
            this Privacy Policy and our Terms of website.
          </p>
          {privacyPolicyArray.map(({ id, head, desc }) => {
            return (
              <div key={id} className="mt-4">
                <h2 className="font-semibold text-xl mb-2">{head}</h2>
                <ul className="my-3">
                  {desc.map((value, index) => {
                    return (
                      <li key={`${id}-${index}`} className="list-disc my-2">
                        {value}
                      </li>
                    );
                  })}
                </ul>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

const privacyPolicyArray = [
  {
    id: 1,
    head: 'Definitions and key terms',
    desc: [
      'To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:',
      `Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.`,
      'Country: where  Our Store or the owners/founders of 123hp-printer are based, in this case is US',
      'Customer: refers to the company, organization or person that signs up to use the 123hp-printer website to manage the relationships with your consumers or website users.',
      'Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit 123hp-printer and use the website.',
      '  Personnel: refers to those individuals who are employed by  Our Store or are under contract to perform a service on behalf of one of the parties.',
      'Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.',
      'You: a person or entity that is registered with  Our Store to use the website.',
    ],
  },
  {
    id: 2,
    head: 'What Information Do We Collect?',
    desc: [
      'We collect information from you when you visit our website, register on our site, place an order, respond to a survey or fill out a form.',
      'Name / Username',
      'Phone Numbers',
      'Email Addresses',
      'Mailing Addresses',
      'Billing Addresses',
    ],
  },
  {
    id: 3,
    head: 'Florida Information Protection Act (FIPA) Compliance:',
    desc: [
      ' Our Store, being registered in Florida, adheres to the provisions of the Florida Information Protection Act (FIPA). This includes ensuring the security and confidentiality of personal information and notifying affected individuals in the event of a data breach, as required by FIPA.',
      'California Consumer Privacy Act (CCPA) Compliance',
      'In addition to FIPA compliance,  Our Store also complies with the California Consumer Privacy Act (CCPA). This legislation grants California residents certain rights regarding their personal information, including the right to know what personal information is being collected, the right to request deletion of personal information, and the right to opt-out of the sale of personal information.',
    ],
  },
  {
    id: 4,
    head: 'Do we share the information we collect with third parties?',
    desc: [
      'We are committed to protecting your privacy. Your mobile number, Email address, mailing Address, Billing address, name and other information are not shared with any third party or affiliates for marketing or promotional purposes. Your privacy and confidentiality are important to us, and we strive to maintain the security of your personal information at all times.',
      'Where and when is information collected from customers and end users?',
      ' Our Store will collect personal information that you submit to us.',
    ],
  },
  {
    id: 5,
    head: 'How Do We Use The Information We Collect?',
    desc: [
      'Any of the information we collect from you may be used in one of the following ways:',
      'To personalize your experience (your information helps us to better respond to your individual needs)',
      'To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)',
      'To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)To process transaction.',
    ],
  },
  {
    id: 6,
    head: 'How Long Do We Keep Your Information?',
    desc: [
      `We keep your information only as long as we need it to provide  Our Store to you and fulfill the purposes described in this policy. When we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory obligations, we’ll either remove it from our systems or depersonalize it so that we can’t identify you.
How Do We Protect Your Information ?`,
      `We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to  Our Store or guarantee that your information on the website may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards. `,
    ],
  },
  {
    id: 7,
    head: 'Is the information collected through the  Our Store secure?  ',
    desc: [
      'We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.',
    ],
  },
  {
    id: 8,
    head: ' Can I update or correct my information?',
    desc: [
      'The rights you have to request updates or corrections to the information  Our Store collects depend on your relationship with  Our Store. Personnel may update or correct their information as detailed in our internal company employment policies.',
      'Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by canceling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain in accordance with this Privacy Policy prior to such update, correction, change or deletion. ',
      `Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable. 
Personnel`,
      'If you are a  Our Store worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. ',
      `You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. 
 General Data Protection Regulation (GDPR) Compliance`,
      `Although our primary customer base is within the US, we recognize the importance of data protection for individuals globally. Therefore, we have implemented measures to comply with the General Data Protection Regulation (GDPR) for users within the European Economic Area (EEA). This includes transparent data collection practices, data subject rights, and secure processing of personal data.`,
    ],
  },
  {
    id: 9,
    head: 'Governing Law',
    desc: [
      `This Privacy Policy is governed by the laws of the US without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.`,
      `The laws of the US, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.`,
      `By using  Our Store or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.`,
    ],
  },
  {
    id: 10,
    head: 'Your Consent',
    desc: [
      `We’ve updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it’s being used. By using our  Our Store, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.
 `,
    ],
  },
  {
    id: 11,
    head: 'Cookies',
    desc: [
      ' Our Store uses “Cookies” to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.',
      'Blocking and disabling cookies and similar technologies',
      `Wherever you’re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and website. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser’s help menu for more information. `,
    ],
  },
  {
    id: 12,
    head: 'Kids’ Privacy',
    desc: [
      'We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.',
      'Changes To Our Privacy Policy',
      `We may change our website and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our website and policies. Unless otherwise required by law, we will notify you (for example, through our website) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the website, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.`,
    ],
  },
];
